//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/AddBomb.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddBombC2S")]
  public partial class AddBombC2S : global::ProtoBuf.IExtensible
  {
    public AddBombC2S() {}
    
    private int _bombType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bombType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bombType
    {
      get { return _bombType; }
      set { _bombType = value; }
    }
    private float _durationTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"durationTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float durationTime
    {
      get { return _durationTime; }
      set { _durationTime = value; }
    }
    private float _damageRange;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"damageRange", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float damageRange
    {
      get { return _damageRange; }
      set { _damageRange = value; }
    }
    private float _startX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"startX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startX
    {
      get { return _startX; }
      set { _startX = value; }
    }
    private float _startY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"startY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startY
    {
      get { return _startY; }
      set { _startY = value; }
    }
    private float _startZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"startZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startZ
    {
      get { return _startZ; }
      set { _startZ = value; }
    }
    private float _endX;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"endX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endX
    {
      get { return _endX; }
      set { _endX = value; }
    }
    private float _endY;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"endY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endY
    {
      get { return _endY; }
      set { _endY = value; }
    }
    private float _endZ;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"endZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endZ
    {
      get { return _endZ; }
      set { _endZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddBombS2CEvt")]
  public partial class AddBombS2CEvt : global::ProtoBuf.IExtensible
  {
    public AddBombS2CEvt() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _bombType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bombType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bombType
    {
      get { return _bombType; }
      set { _bombType = value; }
    }
    private int _bombId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bombId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bombId
    {
      get { return _bombId; }
      set { _bombId = value; }
    }
    private float _startX;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"startX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startX
    {
      get { return _startX; }
      set { _startX = value; }
    }
    private float _startY;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"startY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startY
    {
      get { return _startY; }
      set { _startY = value; }
    }
    private float _startZ;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"startZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float startZ
    {
      get { return _startZ; }
      set { _startZ = value; }
    }
    private float _endX;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"endX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endX
    {
      get { return _endX; }
      set { _endX = value; }
    }
    private float _endY;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"endY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endY
    {
      get { return _endY; }
      set { _endY = value; }
    }
    private float _endZ;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"endZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float endZ
    {
      get { return _endZ; }
      set { _endZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}