//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/OpenBomb.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpemBombS2CEvt")]
  public partial class OpemBombS2CEvt : global::ProtoBuf.IExtensible
  {
    public OpemBombS2CEvt() {}
    
    private int _bombId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bombId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bombId
    {
      get { return _bombId; }
      set { _bombId = value; }
    }
    private OpemBombS2CEvt.OpenBombType _openType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"openType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OpemBombS2CEvt.OpenBombType openType
    {
      get { return _openType; }
      set { _openType = value; }
    }
    private readonly global::System.Collections.Generic.List<OpemBombS2CEvt.BeHitData> _beHitData = new global::System.Collections.Generic.List<OpemBombS2CEvt.BeHitData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"beHitData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OpemBombS2CEvt.BeHitData> beHitData
    {
      get { return _beHitData; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BeHitData")]
  public partial class BeHitData : global::ProtoBuf.IExtensible
  {
    public BeHitData() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _lossHp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"lossHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lossHp
    {
      get { return _lossHp; }
      set { _lossHp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"OpenBombType")]
    public enum OpenBombType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=0)]
      Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Break", Value=1)]
      Break = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}