//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/Player.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddPlayerC2S")]
  public partial class AddPlayerC2S : global::ProtoBuf.IExtensible
  {
    public AddPlayerC2S() {}
    
    private string _modelName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"modelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string modelName
    {
      get { return _modelName; }
      set { _modelName = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddPlayerS2C")]
  public partial class AddPlayerS2C : global::ProtoBuf.IExtensible
  {
    public AddPlayerS2C() {}
    
    private readonly global::System.Collections.Generic.List<AddPlayerS2C.PlayerData> _dataList = new global::System.Collections.Generic.List<AddPlayerS2C.PlayerData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<AddPlayerS2C.PlayerData> dataList
    {
      get { return _dataList; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerData")]
  public partial class PlayerData : global::ProtoBuf.IExtensible
  {
    public PlayerData() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _modelName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"modelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string modelName
    {
      get { return _modelName; }
      set { _modelName = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _killCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddPlayerS2CEvt")]
  public partial class AddPlayerS2CEvt : global::ProtoBuf.IExtensible
  {
    public AddPlayerS2CEvt() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _modelName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"modelName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string modelName
    {
      get { return _modelName; }
      set { _modelName = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private int _killCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount; }
      set { _killCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerDeadS2CEvt")]
  public partial class PlayerDeadS2CEvt : global::ProtoBuf.IExtensible
  {
    public PlayerDeadS2CEvt() {}
    
    private string _deadUsername;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deadUsername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deadUsername
    {
      get { return _deadUsername; }
      set { _deadUsername = value; }
    }
    private string _killerUsername;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"killerUsername", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string killerUsername
    {
      get { return _killerUsername; }
      set { _killerUsername = value; }
    }
    private string _deadNickName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"deadNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deadNickName
    {
      get { return _deadNickName; }
      set { _deadNickName = value; }
    }
    private string _killerNickName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"killerNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string killerNickName
    {
      get { return _killerNickName; }
      set { _killerNickName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}