//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Proto/SyncTransition.proto
namespace ProtoData
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncTransitionC2S")]
  public partial class SyncTransitionC2S : global::ProtoBuf.IExtensible
  {
    public SyncTransitionC2S() {}
    
    private int _targetTransition;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"targetTransition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetTransition
    {
      get { return _targetTransition; }
      set { _targetTransition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SyncTransitionS2C")]
  public partial class SyncTransitionS2C : global::ProtoBuf.IExtensible
  {
    public SyncTransitionS2C() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _targetTransition;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"targetTransition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetTransition
    {
      get { return _targetTransition; }
      set { _targetTransition = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}